[package]
name = "tracy-client-sys"
version = "0.7.0"
authors = ["Simonas Kazlauskas <tracy-sys@kazlauskas.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1"
